export declare const Colors: {
    purple: string;
    border: string;
    secondary: string;
    borderColor: string;
    borderColorDark: string;
    borderFocusedColor: string;
    backgroundGrey: string;
    backgroundGreyMask: string;
    white: string;
    dateGrey: string;
    buttonGrey: string;
    black: string;
    backdropBG: string;
    dividerGrey: string;
    errorHintColor: string;
    statusBarDivider: string;
    sliderBarGrey: string;
    transparent: string;
    settingsGreyText: string;
    settingsBlackText: string;
    settingsStatusText: string;
    settingsButtonDisable: string;
    maskColor: string;
    warnRed: string;
    red: string;
    statusBarGrey: string;
    questionGrey: string;
    openQuestionSubTitle: string;
    sliderShadowColor: string;
    versionGrey: string;
    inputPlaceholder: string;
    progressBarText: string;
    mandatoryRed: string;
    loadingMaskBG: string;
    placeholderText: string;
    defaultThemeColor: string;
    fontColorLight: string;
    fontColorDark: string;
    backgroundColorLight: string;
    backgroundColorDark: string;
    sliderBackgroundDark: string;
    unSelectedBackground: string;
    smileyRatingScoreGray: string;
    appearanceSubBlack: string;
    warningRed: string;
    rankingBorder: string;
    rankingBorderDark: string;
    rankingBG: string;
    rankingBGDark: string;
    rankingContainerBorder: string;
    rankingContainerBorderDark: string;
    rankingContainerBgDark: string;
    divider: string;
    rankingCheckBoxBorder: string;
    sliderLabel: string;
    sliderTrack: string;
    contentBackground: string;
};
export declare const addOpacityToColor: (hexColor: string, opacity: number) => string;
export declare const opacity10: (color: string) => string;
export declare const opacity15: (color: string) => string;
export declare const opacity30: (color: string) => string;
export declare const opacity60: (color: string) => string;
export declare const Option1BackgroundColor: string[];
export declare const Option1BackgroundColorDark: string[];
