export const sdkFetcher: Fetcher;
export function apiGetProgramById(param: any, requestConfig?: any): Promise<any>;
export function apiGetVisibilityById(visibilityId: string, requestConfig?: any): Promise<any>;
export function apiPostEvent(param: any, requestConfig?: any): Promise<any>;
export function apiUploadFileEvent(file: ImageFormData, requestConfig?: any): Promise<import("./UploadFileAPI").UploadFileResult>;
export type APIGetProgramByIdParam = any;
export type APIPostEventParam = any;
export type RequestConfig = any;
export type InitializeParams = any;
export type ImageFormData = import('../lib/UploadFileAPI').ImageFormData;
import { Fetcher } from "./Fetcher";
