export var __esModule: boolean;
export var ActivityIndicatorMask: any;
export var ClassicQuestionContainer: any;
export var Colors: any;
export var EndScreenLayout: any;
export var GlobalStyle: any;
export var KioskProvider: ({ children, themeOption, appearance, fontColor, backgroundColor }: {
    children: any;
    themeOption: any;
    appearance: any;
    fontColor: any;
    backgroundColor: any;
}) => any;
export var KioskProviderProps: any;
export var PlaceholderScreen: any;
export var QuestionContainer: any;
export var StartScreenLayout: any;
export var SurveyProgressBarPosition: any;
export var SurveyScreenLayout: any;
export var i18n: any;
