export var __esModule: boolean;
export var ActivityIndicatorMask: any;
export var COLOR_SCHEMES: any;
export var Colors: any;
export var EndScreenLayout: any;
export var GlobalStyle: any;
export var KioskProvider: ({ children, theme, fontColor, backgroundColor }: {
    children: any;
    theme: any;
    fontColor: any;
    backgroundColor: any;
}) => any;
export var PlaceholderScreen: any;
export var QuestionContainer: any;
export var StartScreenLayout: any;
export var SurveyProgressBarPosition: any;
export var SurveyScreenLayout: any;
export var THEME_OPTIONS: any;
export var i18n: any;
export var useTheme: any;
