export namespace Colors {
    const purple: string;
    const borderColor: string;
    const borderColorDark: string;
    const borderFocusedColor: string;
    const backgroundGrey: string;
    const backgroundGreyMask: string;
    const white: string;
    const dateGrey: string;
    const buttonGrey: string;
    const black: string;
    const dividerGrey: string;
    const errorHintColor: string;
    const statusBarDivider: string;
    const sliderBarGrey: string;
    const transparent: string;
    const settingsGreyText: string;
    const settingsBlackText: string;
    const settingsStatusText: string;
    const settingsButtonDisable: string;
    const maskColor: string;
    const warnRed: string;
    const red: string;
    const statusBarGrey: string;
    const questionGrey: string;
    const openQuestionSubTitle: string;
    const sliderShadowColor: string;
    const versionGrey: string;
    const inputPlaceholder: string;
    const progressBarText: string;
    const mandatoryRed: string;
    const loadingMaskBG: string;
    const placeholderText: string;
    const defaultThemeColor: string;
    const fontColorLight: string;
    const fontColorDark: string;
    const backgroundColorLight: string;
    const backgroundColorDark: string;
    const sliderBackgroundDark: string;
    const unSelectedBackground: string;
    const smileyRatingScoreGray: string;
    const appearanceSubBlack: string;
    const warningRed: string;
}
export function addOpacityToColor(hexColor: any, opacity: any): string;
export function opacity10(color: any): string;
export function opacity15(color: any): string;
export function opacity30(color: any): string;
export function opacity60(color: any): string;
export const Option1BackgroundColor: string[];
export const Option1BackgroundColorDark: string[];
